name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        docker build -t gazdinfoszd .
        docker-compose -f docker-compose.yml up -d

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: docker-image
        path: docker-compose.yml
