name: Gazdinfo

on:
  push:
    tags:
      - 'v*.*.*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Get repository release tag
        id: timeseries
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          excludes: prerelease, draft
          repository: ${{ github.repository }}
      - name: Build Docker image
        run: |
          docker build --network=host -t ${{secrets.DOCKER_USER}}/MY_REPO:latest -t ${{secrets.DOCKER_USER}}/MY_REPO:${{ steps.timeseries.outputs.release }} .
      - name: Docker push image
        run: |
          docker push ${{secrets.DOCKER_USER}}/MY_REPO
          docker push ${{secrets.DOCKER_USER}}/MY_REPO:${{ steps.timeseries.outputs.release }}

        build_and_upload:
          - name: Checkout project
            uses: actions/checkout@v2
            
          - name: Set up Docker Buildx
            id: buildx
            uses: docker/setup-buildx-action@v1
        
          - name: Build and push
            id: docker_build
            uses: docker/build-push-action@v2
            with:
              push: false
              builder: ${{ steps.buildx.outputs.name }}
              tags: "test_image:latest"
              load: true

          - name: Upload image
            uses: ishworkh/container-image-artifact-upload@v1.0.0
            with:
              image: "test_image:latest"