name: Gazdinfoszd
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: lorisleiva/laravel-docker:8.0
    steps:
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-docker@v2

    - name: Build Docker image
      run: |
        docker build -t your-docker-image-name .
        docker-compose up -d

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: docker-image
        path: docker-compose.yml


    